- name: Install Docker on Amazon Linux
  hosts: backend-ec2
  become: yes
  tasks:
    - name: Install required packages (yum)
      yum:
        name: docker
        state: present

    - name: Ensure Docker service is enabled and started
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
